
scalar DateTime

type Thought {
    uuid: ID
    text: String
    createdAt: DateTime
}

# The "Query" type is special: it lists all of the available queries that
# clients can execute, along with the return type for each.
type Query {
    thoughts: [Thought]
}
